### ISSUE TITLE
create_avd_device does not appear to work as described

### ISSUE THREAD

**Issue by dantman** [AzimoLabs/fastlane-plugin-automated-test-emulator-run#13]
When I try using create_avd_device as a label I get this error:
```
[!] Exit status of command 'echo "no" | ~/Library/Android/sdk/tools/bin/avdmanager create avd --name "Test-Phone" --package "system-images;android-25;google_apis;x86" --device "Ephemeral Test Phone" --tag google_apis --abi x86 ' was 1 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
Error: No device found matching --device Ephemeral Test Phone.
```

Presumably the `--device` arg doesn't work the same in `avdmanager` as it did in the old `android avd` tool.

**Comment by rohanmartin** [comment]
Have you checked the device ID exists?
`--device` takes the device id which you can get from `avdmanager list device`. It's the value listed next to `id:`, not `Name:`

> id: 18 or "pixel_c"
>     Name: Pixel C
>     OEM : Google

Would be "pixel_c" not "Pixel C"

**Comment by FisherKK** [comment]
Hi @dantman!

Sorry for late response.

Yeah that's avdmanager related error. It's not plugin fault. 
Try @rohanmartin solution. I was about to answer the same when I saw your question.

**Comment by dantman** [comment]
I know what `--device` does in the current `avdmanager`, my problem is the documentation.

This is what `README.md` says:

> `create_avd_device` - optional label for device e.g. "For plugin tests only. Do not touch."

**Comment by FisherKK** [comment]
Whoops! I am sorry then - it's problem on our side.

Thanks for pointing that. 
I have updated `README.md`.
