### ISSUE TITLE
running screengrab

### ISSUE THREAD

**Issue by joreilly** [AzimoLabs/fastlane-plugin-automated-test-emulator-run#3]
Is it only possible to use `gradle_task` and `shell_task` when using this?  Would be great for example to be able to run `screengrab`.

**Comment by FisherKK** [comment]
Hello,

I have never used `screengrab` but I've just checked GitRepo of this tool. I will take a closer look at it tomorrow, yet I am quite sure that it should work.

You can start other `fastlane` lanes with usage of this tool. So for example you could try something like this:

```
     lane :assemble_apk_and_grab_screenshots do
         gradle(task: "assembleDebug assembleAndroidTest")
         Action.sh("screengrab")
     end

     lane :grab_screenshots do
     	automated_test_emulator_run(
          AVD_setup_path: "fastlane/MyConfigs/AVD_ConfigForScreengrab.json",
          shell_task: "fastlane assemble_apk_and_grab_screenshots"
        )
     end
```

**Comment by joreilly** [comment]
Thanks @FisherKK for the quick response! Will try that out

**Comment by FisherKK** [comment]
Sure :) No problem!
I hope it will work.
