### ISSUE TITLE
Add option to skip reset adb

### ISSUE THREAD

**Issue by SemenovAlexander** [AzimoLabs/fastlane-plugin-automated-test-emulator-run#5]
Thanks for great plugin! 

In our setup - we run tests for couple different projects on single build machine with Jenkins. 

Issue is, plugin restarts adb, because of code here
https://github.com/AzimoLabs/fastlane-plugin-automated-test-emulator-run/blob/master/lib/fastlane/plugin/automated_test_emulator_run/actions/automated_test_emulator_run_action.rb#L74

Restarting adb, while other test run in progress, causes that test run to fail. 

It would be really nice, to be able disable that adb restart via config option.

**Comment by FisherKK** [comment]
Hello!

I have added 'ADB_restart' parameter for you in fastlane. Set it to false and ADB won't restart anymore.

https://github.com/AzimoLabs/fastlane-plugin-automated-test-emulator-run/blob/master/lib/fastlane/plugin/automated_test_emulator_run/actions/automated_test_emulator_run_action.rb#L316

Thank you for using our plugin :)

**Comment by SemenovAlexander** [comment]
Thanks for quick fix, now it works like a charm for me!
